---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weather-agent
  namespace: demo
---
apiVersion: v1
kind: Secret
metadata:
  name: weather-agent-token
  namespace: demo
  annotations:
    kubernetes.io/service-account.name: weather-agent
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-agent
  namespace: demo
---
apiVersion: v1
kind: Secret
metadata:
  name: customer-agent-token
  namespace: demo
  annotations:
    kubernetes.io/service-account.name: customer-agent
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customers-tool
  namespace: demo
---
apiVersion: v1
kind: Secret
metadata:
  name: customers-tool-token
  namespace: demo
  annotations:
    kubernetes.io/service-account.name: customers-tool
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weather-tool
  namespace: demo
---
apiVersion: v1
kind: Secret
metadata:
  name: weather-tool-token
  namespace: demo
  annotations:
    kubernetes.io/service-account.name: weather-tool
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chat-ui
  namespace: demo
---
apiVersion: v1
kind: Secret
metadata:
  name: chat-ui-token
  namespace: demo
  annotations:
    kubernetes.io/service-account.name: chat-ui
type: kubernetes.io/service-account-token
