---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weather-agent
  namespace: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-agent
  namespace: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customers-tool
  namespace: demo
