---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customers-tool
  namespace: demo
---
apiVersion: v1
kind: Secret
metadata:
  name: customers-tool-token
  namespace: demo
  annotations:
    kubernetes.io/service-account.name: customers-tool
type: kubernetes.io/service-account-token
