---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-agent
  namespace: demo
---
apiVersion: v1
kind: Secret
metadata:
  name: customer-agent-token
  namespace: demo
  annotations:
    kubernetes.io/service-account.name: customer-agent
type: kubernetes.io/service-account-token
