---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: demo-auth
  namespace: demo
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: demo-role
    serviceAccount: default
